apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAhop+J
  GITHUB_TOKEN: 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
