apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
  labels:
    rhdh.redhat.com/ext-config-sync: "true"
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: '@backstage/plugin-scaffolder-backend-module-github'
        disabled: false
