---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
  labels:
    app.kubernetes.io/name: backstage
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: BACKEND_SECRET
          valueFrom:
            secretKeyRef:
              name: rhdh-secrets
              key: BACKEND_SECRET
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: rhdh-secrets
              key: GITHUB_TOKEN
    replicas: 1
    route:
      enabled: true
      host: rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io
      subdomain: apps.cluster-klj6r.dynamic.redhatworkshops.io
  database:
    enableLocalDb: true
...
