---
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: demo-project
  labels:
    app.kubernetes.io/name: backstage
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: dynamic-plugins-rhdh
      mountPath: /opt/app-root/src
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: rhdh-secrets
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
      host: rhdh.apps.cluster-klj6r.dynamic.redhatworkshops.io
      subdomain: apps.cluster-klj6r.dynamic.redhatworkshops.io
  database:
    enableLocalDb: true
...
